import { ModulsTypes } from 'modules';

// ========= USERS ACTIONS BEGIN =========
export const PASSWORD_LOGIN = 'PASSWORD_LOGIN';
export const PASSWORD_LOGIN_REQUEST = 'PASSWORD_LOGIN_REQUEST';
export const PASSWORD_LOGIN_SUCCESS = 'PASSWORD_LOGIN_SUCCESS';
export const PASSWORD_LOGIN_FAILURE = 'PASSWORD_LOGIN_FAILURE';

export const REFRESH_LOGIN = 'REFRESH_LOGIN';
export const ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID';
export const REFRESH_LOGIN_REQUEST = 'REFRESH_LOGIN_REQUEST';
export const REFRESH_LOGIN_SUCCESS = 'REFRESH_LOGIN_SUCCESS';
export const REFRESH_LOGIN_FAILURE = 'REFRESH_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
// ========= USERS ACTIONS END =========

// ========= TOPICS ACTIONS BEGIN =========
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';

export const CREATE_TOPIC = 'CREATE_TOPIC';
export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';

export const UPDATE_TOPIC = 'UPDATE_TOPIC';
export const UPDATE_TOPIC_REQUEST = 'UPDATE_TOPIC_REQUEST';
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS';
export const UPDATE_TOPIC_FAILURE = 'UPDATE_TOPIC_FAILURE';


export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const START_TOPIC = 'START_TOPIC';
export const STOP_TOPIC = 'STOP_TOPIC';
export const TYPING = 'TYPING';
// ========= TOPICS ACTIONS END =========

// ========= TICK ACTIONS BEGIN =========
export const TICK_EVENT = 'TICK_EVENT';
export const TICK_START = 'TICK_START';
export const TICK_STOP = 'TICK_STOP';
// ========= TICK ACTIONS END =========